### ISSUE TITLE
Build and deploy stable release binaries to the CDN

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/qa-cli#1]
As one of the binary distribution channels consider establishing of an infrastructure to build and deploy the binary to https://storage.googleapis.com or any other CDN.

**Comment by phyrog** [comment]
https://github.com/kyma-project/qa-cli/pull/5 will create a new GitHub release when a new git tag is pushed, build binaries for Linux and Mac (both for amd64 + arm64) and upload/attach them to the release.

**Comment by tobiscr** [comment]
Pandas team is discontinued... closing the issue is fine.
